# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/37fda4d0-a460-4d69-931d-055a3d726802";
      fsType = "btrfs";
      options = "compress=lzo,discard,defaults,ssd";
    };

  fileSystems."/mnt/windows/" =
    { device = "/dev/disk/by-uuid/766658266657E601";
      fsType = "ntfs";
      options = "defaults,windows_names";
    };

  fileSystems."/mnt/windowsData/" =
    { device = "/dev/disk/by-uuid/567404EE7404D2A3";
      fsType = "ntfs";
      options = "defaults,windows_names";
    };

  fileSystems."/boot" = {
      device = "/dev/sdb2";
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/fa000d98-6212-414a-af29-dd93cc9485d0"; } ];

  nix.maxJobs = 4;
  nix.buildCores = 4;
}
